import {Settings} from "./settings";

/* Defines the Config entity*/
export const emptySettings : Settings = {
    myAddress: '',
    partnerPrintType: 'label',
    labelWidth: '10',
    labelHeight: '5.5',
    defaultTab: 0,
    logoInBottom: false,
    logoWidth: '3',
    addressTopMargin: '2',
    addressLeftMargin: '0',
    addressRightMargin: '0',
    addressBottomMargin: '0',
    addressDefaultFontSize: 17,
    addressWidth: '9',
    textBeforeAddress: '',
    languageDirection: 'ltr',
    paperSize: '21.0X29.7',
    paperMargin: '1',
    paperMarginTop: '1',
    paperMarginBottom: '1',
    paperMarginLeft: '1',
    paperMarginRight: '1',
    multiAddressPerPage: false,
    repeatAddress: false,
    numAddressPerRow: 3,
    numAddressPerColumn: 7,
    cellPaddingLeft: 0,
    cellPaddingRight: 0,
};